name: Notify Remote Providers
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  notify-meshmap-build:
    name: Notify Meshmap Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger plugins for edge
      if: startsWith(github.ref, 'refs/tags/') != true && success()
      uses: kumarabd/trigger-remote-action@master
      with:
        name: "Build and Publish"
        repo: layer5labs/meshery-extensions
        token: ${{ secrets.GITHUB_PAT }}
        version: master
    - name: trigger plugins for release
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      uses: kumarabd/trigger-remote-action@master
      with:
        name: "Build and Publish"
        repo: layer5labs/meshery-extensions
        token: ${{ secrets.GITHUB_PAT }}
        version: ${GITHUB_REF/refs\/tags\//}